### ISSUE TITLE
allowed memory

### ISSUE THREAD

**Issue by carlituxman** [simoebenhida/laravel-intellisense#10]
when enable this extension the cpu gets 100% and PHP Fatal error:  Allowed memory size...

**Comment by simoebenhida** [comment]
@carlituxman Is it also happening on the latest version 0.1.3?

**Comment by carlituxman** [comment]
yes, 0.1.3

**Comment by simoebenhida** [comment]
Can I get a screenshot of your CPU or the script where the exception is happening?
