### ISSUE TITLE
I have tried every tutorial but ntellisense is not working

### ISSUE THREAD

**Issue by khanakia** [simoebenhida/laravel-intellisense#17]
Hi,
I am using Macbook with Visual Studio Code. I have installed and followed every instructions but still i am unable to work the auto suggestions.

So basically **Eloquent Autocompletion and route** autocompletion not working all others are working.

**Comment by simoebenhida** [comment]
Hi @khanakia!
What are you using on your development environment (Valet - Docker - Homestead ..)?

**Comment by khanakia** [comment]
@simoebenhida 
No i am not using any Development Environment. I am using simple Laravel PHP installation on my local macbook.
Please check the below link i have created a video.

https://www.dropbox.com/s/la4lv60nncjwr8o/Screen%20Recording%202020-07-20%20at%209.08.15%20AM.mov?dl=0

**Comment by simoebenhida** [comment]
What do you get when you run:
```
php artisan tinker
App\User::first();
```

**Comment by khanakia** [comment]
> What do you get when you run:
> 
> ```
> php artisan tinker
> App\User::first();
> ```

Please check the screenshot.

<img width="656" alt="Screenshot 2020-07-20 at 9 49 24 AM" src="https://user-images.githubusercontent.com/2174170/87899283-5638d580-ca6e-11ea-9528-6d1569fd5df2.png">

**Comment by simoebenhida** [comment]
Hmm, it looks good!
Can I get a screenshot of your vscode process explorer when writing the query autocompletion 
<img width="495" alt="Screen Shot 2020-07-20 at 05 27 30" src="https://user-images.githubusercontent.com/19809072/87899772-1cee6e80-ca4a-11ea-9238-9fa76691aafd.png">

**Comment by khanakia** [comment]
> Hmm, it looks good!
> Can I get a screenshot of your vscode process explorer when writing the query autocompletion
> <img alt="Screen Shot 2020-07-20 at 05 27 30" width="495" src="https://user-images.githubusercontent.com/19809072/87899772-1cee6e80-ca4a-11ea-9238-9fa76691aafd.png">

Please find the video link

https://www.dropbox.com/s/la4lv60nncjwr8o/Screen%20Recording%202020-07-20%20at%209.08.15%20AM.mov?dl=0

**Comment by simoebenhida** [comment]
Sorry! I couldn't see the process explorer on the video! I think you sent me the first video again

**Comment by khanakia** [comment]
Sorry. Check this one https://www.dropbox.com/s/xwybctisu96pja1/Screen%20Recording%202020-07-20%20at%2010.11.22%20AM.mov?dl=0

**Comment by simoebenhida** [comment]
Thanks! It looks that the script is not even fired!
Hmm, make sure that the `user` table has at least one record! Because the package gets the columns from the database!

Also, the autocompletion will not happen when you do `whenColumn('')` because it autocompletes columns after all!

**Comment by simoebenhida** [comment]
From looking at `web.php` it makes sense that you don't have any route autocompletion! You should have named routes!

**Comment by khanakia** [comment]
@simoebenhida  Thank you very much 💯 👍 

It worked. You should have mentioned this on the docs also. So new users will know that it will only work with named routes instead of opening a issue.

<img width="780" alt="Screenshot 2020-07-23 at 7 07 29 AM" src="https://user-images.githubusercontent.com/2174170/88245037-43631280-ccb3-11ea-84aa-902dd806717a.png">

**Comment by simoebenhida** [comment]
@khanakia glad it works! Yeah, I mentioned the database thing on the Readme! Feel free to contribute if you think it needs something else!
