### ISSUE TITLE
Command 'Generate Ide Helper' resulted in an error (command 'generate_ide_helper' not found)

### ISSUE THREAD

**Issue by RyanAidilPratama** [simoebenhida/laravel-intellisense#24]
I tried installing this extension last night. However, whenever I try to run the "Generate Ide Helper" command I always get an error. How can I fix it?
![image](https://user-images.githubusercontent.com/43450710/94154689-c02b8c00-feb0-11ea-91da-b2dfba2b6861.png) ![image](https://user-images.githubusercontent.com/43450710/94154687-bf92f580-feb0-11ea-8af7-4ab565db59c2.png)

**Comment by simoebenhida** [comment]
Hi @RyanAidilPratama 
Couldn't duplicate the issue! What about when closing vscode and opening it again?

**Comment by RyanAidilPratama** [comment]
> 
> 
> Hi @RyanAidilPratama
> Couldn't duplicate the issue! What about when closing vscode and opening it again?

I've tried everything from closing vscode and opening it again, uninstall and reinstall the extension, install another version of the extension, even restarting my laptop. But none of that seems to be working.

**Comment by Sethios** [comment]
Tried installing it for the first time and got this same exact issue.
Tried everything as Ryan and no luck.

Here is my VSC "About" dump if it helps in any way.:

Version: 1.49.2 (system setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by albertoelias123** [comment]
I have the same problem, install Laravel Ide Helper MANUALLY and run all the necessary commands but the extension still didn't work.

Php Inteliphense was able to help me a little with some suggestions, attributes and methods. However it does not come close to the proposal of this extension, assist with Eloquent, Factory, View, etc.

I am using Laravel 8.x.

**Comment by simoebenhida** [comment]
@RyanAidilPratama Are you not missing the `artisan` file on the root folder of laravel application?

**Comment by RyanAidilPratama** [comment]
> 
> 
> @RyanAidilPratama Are you not missing the `artisan` file on the root folder of laravel application?

No, I still have it in my root folder. This happening even in a fresh installation of Laravel.

Here is my VSC about dump:
Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by simoebenhida** [comment]
I tried it on a fresh installation for laravel 8! For the command to work! The path project should have `artisan` file! This is how I detect if is a laravel project for now! Unless if you have a better approach!

**Comment by zeydduran** [comment]
i have the same problem

**Comment by simoebenhida** [comment]
It should be good on the last release!

After checking it looked that the issue was only on windows! For some reason `uri.path` adds an `/` at the first of the path on windows so changed it to `fsPath` 

Thanks to everyone for reporting the issue 😊

**Comment by RyanAidilPratama** [comment]
It worked perfectly now, thanks for the fix 👍👍

**Comment by AngelinCalu** [comment]
Still encountering the same problem. With the latest version of VSCode and a fresh installation of the package.
