### ISSUE TITLE
How to get autocompletion eloquent ? 

### ISSUE THREAD

**Issue by lukjon** [simoebenhida/laravel-intellisense#26]
how to achieve autocompletion in eloquent ? 
![image](https://user-images.githubusercontent.com/28525322/99695726-9056ca00-2a96-11eb-92e8-0b95bf4477fc.png)

**Comment by simoebenhida** [comment]
Hi @lukjon 
You should have the database connected so it can get attributes from there!

Check this if you are using docker:
https://github.com/simoebenhida/laravel-intellisense#docker

If your model namespace is not the default one (App)! try to change the namespace on settings

**Comment by lukjon** [comment]
I have tried, but unfortunately, I am not able to get properties. I am not sure what could be wrong. All the migrations are in the database. Do you know what could be wrong?

![image](https://user-images.githubusercontent.com/28525322/99693844-7916dd00-2a94-11eb-837b-5e51a49326f3.png)


.env file
![image](https://user-images.githubusercontent.com/28525322/99693305-e1b18a00-2a93-11eb-9db8-5b4e753415c7.png)

**Comment by derianmarchan** [comment]
Tengo el mismo problema aunque en laravel 8 el path ah cambiado de App a App\Models ya le actualize y nada
![image](https://user-images.githubusercontent.com/69947872/99706443-0f350e00-2a69-11eb-8bbf-a50cdef6b826.png)
Las propiedades generadas lucen así
![image](https://user-images.githubusercontent.com/69947872/99706343-ead93180-2a68-11eb-8525-8fb9423d6531.png)
Normal funciona el _id_helper.php porque me autocompleta los métodos es este caso el "where"
![image](https://user-images.githubusercontent.com/69947872/99707058-f547fb00-2a69-11eb-8fa8-682185435d64.png)
Pero la extensión que dice mostrar los campos del modelo no funciona
![image](https://user-images.githubusercontent.com/69947872/99707608-b1092a80-2a6a-11eb-95da-20649bafe783.png)
Mi modelo generados por el IDE HELPER en _ide_helper_models.php  para la clase en especifico luce así
![image](https://user-images.githubusercontent.com/69947872/99707808-f3326c00-2a6a-11eb-9c0e-87362aa37090.png)
 Utilizo la `extensión` <a href="https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client">PHP Intelephense</a> No se dónde estará el problema. Si en la configuración o será por la versión de laravel(8)

**Comment by lukjon** [comment]
Same for me, too

**Comment by simoebenhida** [comment]
@lukjon @derianmarchan Sorry couldn't duplicate the issue on laravel 8! It also works fine there! Just make sure you have already some data on your tables! For example, check if `UserType` table already has records on the database

**Comment by AlexKomMsk** [comment]
It's the same for me. Doesn't work for routes, views, configs, etc. I am using Laravel 8, Laragon, Windows 10. The database is connected. What could be the problem?

**Comment by simoebenhida** [comment]
Sorry i managed to duplicate the issue on Windows! It is not working properly there! Working on it ...

**Comment by simoebenhida** [comment]
It should be fixed on the last release 0.2.0
