### ISSUE TITLE
Intellisense not work at all

### ISSUE THREAD

**Issue by apt42541** [simoebenhida/laravel-intellisense#31]
![image](https://user-images.githubusercontent.com/12625408/104830172-da99d300-58ae-11eb-9162-1d4c8496ed6e.png)
![image](https://user-images.githubusercontent.com/12625408/104830189-ef766680-58ae-11eb-980f-2cca7c9b1a42.png)
i just try laravel intellisense extension , do i have to setting more?

**Comment by simoebenhida** [comment]
Hi @apt42541 
The extension helps you autocomplete model attributes! Like when writing `where('` you get the model attributes.

For functions install https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
