### ISSUE TITLE
have support for multi model paths

### ISSUE THREAD

**Issue by ctf0** [simoebenhida/laravel-intellisense#32]
so it can work with something like https://nwidart.com/laravel-modules/v6/introduction

**Comment by simoebenhida** [comment]
Hi @ctf0 
That is a great idea! Will keep the issue open until it is resolved

**Comment by mikebronner** [comment]
This is especially important if you use DDD and structure your folders by domain, each with their own models folder, or if you use event sourcing and structure everything around domains, each with their own projections folder. Also, perhaps there is a better way to detect models, as we don't get autocompletion on non-app models, like those from Illuminate or 3rd-party packages.
