### ISSUE TITLE
How to generate ide helper

### ISSUE THREAD

**Issue by tanthammar** [simoebenhida/laravel-intellisense#4]
The docs says I can write this command, but where??
(tried it in terminal, in project root folder)

> The package will help you generate a default ide helper file by just writing this command:
```
Generate Ide Helper
```

**Comment by simoebenhida** [comment]
@tanthammar Yeah you need to launch the vscode command palette with: 
```
Macbook:
Shift + Command + P

Windows:
Ctrl+Shift+P
```

Sorry for not being more specific on the Readme! Feel free to add some improvements there if you want too!
