### ISSUE TITLE
cpu resource become 100%

### ISSUE THREAD

**Issue by jhonoryza** [simoebenhida/laravel-intellisense#5]
i am using with latest vscode, after enable this library my cpu resource become 100% and hangup my laptop

**Comment by djekl** [comment]
Yeah, I am having the same issue. 100% CPU usage, looks to be running multiple PHP processes

![image](https://user-images.githubusercontent.com/1119714/84758879-e8f0db00-afbd-11ea-8318-f54ea4f89287.png)

**Comment by simoebenhida** [comment]
Thanks @jhonoryza @djekl for reporting the issue!

I couldn't reproduce the issue! @djekl can I get the full line of code from one of those scripts in that screenshot, please!

**Comment by djekl** [comment]
@simoebenhida I had open a fresh Laravel 7 install open for that screenshot. Had open a few source files from Laravel, the default controller, and the web route file.

**Comment by simoebenhida** [comment]
@djekl What are you using to host the laravel project? (Docker/Homestead/Valet..) ?

**Comment by djekl** [comment]
Local dev is Valet. To reproduce for that screenshot, I opened VS Code with all addons disabled, then re-enabled yours with a virgin L7 project open. Nothing done to it. Opened a few files, left for about 5-7 minutes (make a coffee), and come back to CPU pinned.

**Comment by simoebenhida** [comment]
I just did the same exact thing and didn't see those records!

![Screen Shot 2020-06-16 at 22 01 02](https://user-images.githubusercontent.com/19809072/84827788-e2de1700-b01c-11ea-8190-11c407fbc476.png)
