### ISSUE TITLE
Crashes system with vapor deploy

### ISSUE THREAD

**Issue by makopov** [simoebenhida/laravel-intellisense#9]
Shortly after enabling this plugin, I would do a `vapor deploy production` and my system would spin up a ton of PHP processes, run the cpu at 100% and eventually crash. After disabling this plugin (or leaving VScode closed) the problem went away. I'm not sure why this happens. I've attached a screenshot of my process list when the cpu is pegged at 100%
<img width="1685" alt="Screen Shot 2020-06-16 at 2 12 31 PM" src="https://user-images.githubusercontent.com/1185010/84955005-4ca50200-b0ab-11ea-87a9-376ef95253e9.png">

**Comment by simoebenhida** [comment]
@makopov Is it still happening on the latest version 0.1.3?

**Comment by makopov** [comment]
Just reinstalled it to try it out, seems to be okay. What was causing it?

**Comment by simoebenhida** [comment]
It was running multiple scripts at once! Removed that option so now it is only running one script at a time!

But still didn't get the main issue why it is running all those scripts at once since I couldn't reproduce it!
